# ¿Que es PyTorch?

Es un paquete científico basado en Python dirigido a dos grupos de audiencias:
<\br>
+ Un reemplazo de Numpy para usar la potencia de las GPU.
+ Una plataforma de investigación de aprendizaje profundo que proporciona la máxima flexibilidad y velocidad.  
  
Los tensores son similares a los ndarrays de numpy, con la adición de que los tensores también se pueden usar en una GPU para acelerar la computación.

In [1]:
from __future__ import print_function
import torch

Construimos una matriz de 5 x 3, sin inicializar.

In [3]:
x = torch.Tensor(5, 3)
print(x)


 5.7094e+03  4.5883e-41  8.2102e-38
 0.0000e+00  0.0000e+00  4.5569e-41
 1.0507e-35  4.5883e-41  0.0000e+00
 0.0000e+00  2.5788e-09  1.1478e-08
 1.0921e-05  4.6317e+01  1.0804e+27
[torch.FloatTensor of size 5x3]



Ahora una matriz inicializada aleatoriamente.

In [6]:
x = torch.rand(5, 3)
print(x)
print(x.size())  # Es una tupla


 0.0607  0.7432  0.2581
 0.5441  0.2460  0.5132
 0.1503  0.2121  0.8049
 0.8923  0.0936  0.4527
 0.8089  0.9082  0.0603
[torch.FloatTensor of size 5x3]

torch.Size([5, 3])


### Operaciones.  
Para las operaciones tenemos varias sintaxis. Como ejemplo tomamos la suma.

In [7]:
y = torch.rand(5, 3)
print(x+y)


 1.0085  1.6322  1.1861
 1.0865  0.5866  0.9083
 0.3363  1.0146  0.8128
 1.3519  0.5747  0.4616
 1.3497  0.9204  0.1923
[torch.FloatTensor of size 5x3]



In [8]:
print(torch.add(x, y))


 1.0085  1.6322  1.1861
 1.0865  0.5866  0.9083
 0.3363  1.0146  0.8128
 1.3519  0.5747  0.4616
 1.3497  0.9204  0.1923
[torch.FloatTensor of size 5x3]



In [9]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.0085  1.6322  1.1861
 1.0865  0.5866  0.9083
 0.3363  1.0146  0.8128
 1.3519  0.5747  0.4616
 1.3497  0.9204  0.1923
[torch.FloatTensor of size 5x3]



In [12]:
y.add_(x)
print(y)


 1.0085  1.6322  1.1861
 1.0865  0.5866  0.9083
 0.3363  1.0146  0.8128
 1.3519  0.5747  0.4616
 1.3497  0.9204  0.1923
[torch.FloatTensor of size 5x3]



Toda operación que cambia el tensor original se denota con guión bajo ( _ ). 

Convertir un Tensor de torch en una matriz numpy y viceversa es muy fácil.
  
El Tensor y el numpy array compartirán sus ubicaciones de memoria subyacentes, y cambiar una cambiará la otra.

In [15]:
a = torch.ones(5)
b = a.numpy()
print(a)
print(b)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[ 1.  1.  1.  1.  1.]


Veamos como cambiar uno, cambia tambien el otro.

In [16]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [17]:
import numpy as np
a = np.ones(4)
b = torch.from_numpy(a)
# Modifiquemos el array.
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.]

 2
 2
 2
 2
[torch.DoubleTensor of size 4]



## Tensores en CUDA

In [ ]:
# Corre unicamente si CUDA esta disponible
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y