* Aprendizaje supervisado para problemas de regresión y clasificación
* Representar los pundo de la muestra en el espacio, luego se separa en clases lo más amplio posible mediante un hiperplano de separación llamado vector de soporte.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_style('darkgrid')

In [2]:
data = sns.load_dataset('iris')
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
data['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [5]:
y = data['species']
x = data.drop('species', axis=1)

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=17)

In [9]:
model = SVC(gamma='auto')
model.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
predicciones = model.predict(x_test)

In [12]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       1.00      1.00      1.00        19
   virginica       1.00      1.00      1.00        14

   micro avg       1.00      1.00      1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [13]:
print(confusion_matrix(y_test, predicciones))

[[12  0  0]
 [ 0 19  0]
 [ 0  0 14]]
